module.exports = {
    menu: require('./menu'),
    donasi: require('./donasi'),
    info: require('./info'),
    alay: require('./alay'),
    artinama: require('./artinama'),
    corona: require('./corona'),
    downloadImage: require('./downloadImage'),
    igStalk: require('./igStalk'),
    jodoh: require('./jodoh'),
    jsholat: require('./jsholat'),
    lirik: require('./lirik'),
    nulis: require('./nulis'),
    readTextInImage: require('./ocr'),
    pantun: require('./pantun'),
    quotes: require('./quotes'),
    searchYoutube: require('./searchYoutube'),
    surah: require('./surah'),
    tiktokdl: require('./tiktokdl'),
    tweetdl: require('./tweetdl'),
    wiki: require('./wiki'),
    ytdl: require('./ytdl')
}
